"""phase14: contracts + lease ifrs16

Revision ID: 0e4bf3e82bc0
Revises: 17d7ae8f7655
Create Date: 2026-05-11 14:35:02.978744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e4bf3e82bc0'
down_revision: Union[str, None] = '17d7ae8f7655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
