"""phase6: abc inventory + dashboards + sla + privacy

Revision ID: 10f083bd1557
Revises: b446a7c7b2f7
Create Date: 2026-05-10 10:06:54.911352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10f083bd1557'
down_revision: Union[str, None] = 'b446a7c7b2f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sla_hours', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('due_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('escalate_to_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('escalated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_approval_steps_due_at'), ['due_at'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_approval_steps_escalate_to_id_users'), 'users', ['escalate_to_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_steps', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_approval_steps_escalate_to_id_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_approval_steps_due_at'))
        batch_op.drop_column('escalated_at')
        batch_op.drop_column('escalate_to_id')
        batch_op.drop_column('due_at')
        batch_op.drop_column('sla_hours')

    # ### end Alembic commands ###
