"""phase13: assets_transfer_audit + compliance + drip_sequences

Revision ID: 17d7ae8f7655
Revises: 4d30ecc36074
Create Date: 2026-05-11 14:01:00.101094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17d7ae8f7655'
down_revision: Union[str, None] = '4d30ecc36074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
