"""phase9: rfq + responses + lines

Revision ID: 1d5341fc1481
Revises: f1ff44bb143b
Create Date: 2026-05-11 11:02:13.076074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d5341fc1481'
down_revision: Union[str, None] = 'f1ff44bb143b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
