"""fiscal_period, warehouse, billing, payroll, leave, BOM, report_builder, totp, audit_diff

Revision ID: 285867c39a1b
Revises: 6401f620efdf
Create Date: 2026-05-10 02:58:23.310904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '285867c39a1b'
down_revision: Union[str, None] = '6401f620efdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inv_warehouses',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inv_warehouses'))
    )
    with op.batch_alter_table('inv_warehouses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inv_warehouses_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_inv_warehouses_id'), ['id'], unique=False)

    op.create_table('fin_fiscal_periods',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('closed_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], name=op.f('fk_fin_fiscal_periods_closed_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fin_fiscal_periods')),
    sa.UniqueConstraint('code', name='uq_fiscal_period_code')
    )
    with op.batch_alter_table('fin_fiscal_periods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fin_fiscal_periods_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_fin_fiscal_periods_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fin_fiscal_periods_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fin_fiscal_periods_start_date'), ['start_date'], unique=False)

    op.create_table('inv_warehouse_stock',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('avg_cost', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inv_items.id'], name=op.f('fk_inv_warehouse_stock_item_id_inv_items')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['inv_warehouses.id'], name=op.f('fk_inv_warehouse_stock_warehouse_id_inv_warehouses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inv_warehouse_stock'))
    )
    with op.batch_alter_table('inv_warehouse_stock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inv_warehouse_stock_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inv_warehouse_stock_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inv_warehouse_stock_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('mfg_boms',
    sa.Column('finished_item_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('output_quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['finished_item_id'], ['inv_items.id'], name=op.f('fk_mfg_boms_finished_item_id_inv_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mfg_boms'))
    )
    with op.batch_alter_table('mfg_boms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mfg_boms_finished_item_id'), ['finished_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mfg_boms_id'), ['id'], unique=False)

    op.create_table('report_definitions',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('spec', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_report_definitions_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_definitions'))
    )
    with op.batch_alter_table('report_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_definitions_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_report_definitions_id'), ['id'], unique=False)

    op.create_table('hr_leave_balances',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('annual', 'sick', 'personal', 'maternity', 'other', name='leavetype'), nullable=False),
    sa.Column('entitled_days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('used_days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['hr_employees.id'], name=op.f('fk_hr_leave_balances_employee_id_hr_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hr_leave_balances')),
    sa.UniqueConstraint('employee_id', 'year', 'type', name='uq_leave_balance')
    )
    with op.batch_alter_table('hr_leave_balances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hr_leave_balances_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hr_leave_balances_id'), ['id'], unique=False)

    op.create_table('hr_leave_requests',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('annual', 'sick', 'personal', 'maternity', 'other', name='leavetype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='leavestatus'), nullable=False),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('decided_comment', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], name=op.f('fk_hr_leave_requests_decided_by_id_users')),
    sa.ForeignKeyConstraint(['employee_id'], ['hr_employees.id'], name=op.f('fk_hr_leave_requests_employee_id_hr_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hr_leave_requests'))
    )
    with op.batch_alter_table('hr_leave_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hr_leave_requests_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hr_leave_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hr_leave_requests_status'), ['status'], unique=False)

    op.create_table('hr_payrolls',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('period_code', sa.String(length=7), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bonus', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('allowance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deduction', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('income_tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_pay', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('draft', 'issued', 'paid', name='payrollstatus'), nullable=False),
    sa.Column('paid_at', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['hr_employees.id'], name=op.f('fk_hr_payrolls_employee_id_hr_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hr_payrolls')),
    sa.UniqueConstraint('employee_id', 'period_code', name='uq_payroll_per_employee_period')
    )
    with op.batch_alter_table('hr_payrolls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hr_payrolls_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hr_payrolls_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hr_payrolls_period_code'), ['period_code'], unique=False)

    op.create_table('mfg_bom_components',
    sa.Column('bom_id', sa.Integer(), nullable=False),
    sa.Column('component_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity_per', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bom_id'], ['mfg_boms.id'], name=op.f('fk_mfg_bom_components_bom_id_mfg_boms')),
    sa.ForeignKeyConstraint(['component_item_id'], ['inv_items.id'], name=op.f('fk_mfg_bom_components_component_item_id_inv_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mfg_bom_components'))
    )
    with op.batch_alter_table('mfg_bom_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mfg_bom_components_bom_id'), ['bom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mfg_bom_components_id'), ['id'], unique=False)

    op.create_table('mfg_work_orders',
    sa.Column('wo_no', sa.String(length=50), nullable=False),
    sa.Column('bom_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('status', sa.Enum('draft', 'released', 'in_progress', 'completed', 'cancelled', name='workorderstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bom_id'], ['mfg_boms.id'], name=op.f('fk_mfg_work_orders_bom_id_mfg_boms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mfg_work_orders'))
    )
    with op.batch_alter_table('mfg_work_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mfg_work_orders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mfg_work_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_mfg_work_orders_wo_no'), ['wo_no'], unique=True)

    op.create_table('billing_invoices',
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=True),
    sa.Column('issued_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'issued', 'partially_paid', 'paid', 'overdue', 'cancelled', name='invoicestatus'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['sales_customers.id'], name=op.f('fk_billing_invoices_customer_id_sales_customers')),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], name=op.f('fk_billing_invoices_sales_order_id_sales_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_invoices'))
    )
    with op.batch_alter_table('billing_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_invoices_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_invoices_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_invoices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_invoices_invoice_no'), ['invoice_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_billing_invoices_status'), ['status'], unique=False)

    op.create_table('billing_quotes',
    sa.Column('quote_no', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=False),
    sa.Column('expires_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'sent', 'accepted', 'rejected', 'expired', name='quotestatus'), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('converted_order_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['converted_order_id'], ['sales_orders.id'], name=op.f('fk_billing_quotes_converted_order_id_sales_orders')),
    sa.ForeignKeyConstraint(['customer_id'], ['sales_customers.id'], name=op.f('fk_billing_quotes_customer_id_sales_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_quotes'))
    )
    with op.batch_alter_table('billing_quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_quotes_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_quotes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_quotes_quote_no'), ['quote_no'], unique=True)

    op.create_table('billing_invoice_items',
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['billing_invoices.id'], name=op.f('fk_billing_invoice_items_invoice_id_billing_invoices')),
    sa.ForeignKeyConstraint(['item_id'], ['inv_items.id'], name=op.f('fk_billing_invoice_items_item_id_inv_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_invoice_items'))
    )
    with op.batch_alter_table('billing_invoice_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_invoice_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_invoice_items_invoice_id'), ['invoice_id'], unique=False)

    op.create_table('billing_payments',
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('paid_at', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['billing_invoices.id'], name=op.f('fk_billing_payments_invoice_id_billing_invoices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_payments'))
    )
    with op.batch_alter_table('billing_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_payments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_payments_invoice_id'), ['invoice_id'], unique=False)

    op.create_table('billing_quote_items',
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inv_items.id'], name=op.f('fk_billing_quote_items_item_id_inv_items')),
    sa.ForeignKeyConstraint(['quote_id'], ['billing_quotes.id'], name=op.f('fk_billing_quote_items_quote_id_billing_quotes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_quote_items'))
    )
    with op.batch_alter_table('billing_quote_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_quote_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_quote_items_quote_id'), ['quote_id'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diff', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('resource_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('resource_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_type'), ['resource_type'], unique=False)

    with op.batch_alter_table('inv_movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('unit_cost', sa.Numeric(precision=14, scale=4), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_inv_movements_warehouse_id_inv_warehouses'), 'inv_warehouses', ['warehouse_id'], ['id'])

    with op.batch_alter_table('user_module_permissions', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('admin', 'manager', 'staff', 'viewer', 'supplier', name='role'),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('totp_enabled', sa.Boolean(), nullable=False))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('admin', 'manager', 'staff', 'viewer', 'supplier', name='role'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('admin', 'manager', 'staff', 'viewer', 'supplier', name='role'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
        batch_op.drop_column('totp_enabled')
        batch_op.drop_column('totp_secret')

    with op.batch_alter_table('user_module_permissions', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('admin', 'manager', 'staff', 'viewer', 'supplier', name='role'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)

    with op.batch_alter_table('inv_movements', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_inv_movements_warehouse_id_inv_warehouses'), type_='foreignkey')
        batch_op.drop_column('unit_cost')
        batch_op.drop_column('warehouse_id')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_id'))
        batch_op.drop_column('resource_id')
        batch_op.drop_column('resource_type')
        batch_op.drop_column('diff')

    with op.batch_alter_table('billing_quote_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_quote_items_quote_id'))
        batch_op.drop_index(batch_op.f('ix_billing_quote_items_id'))

    op.drop_table('billing_quote_items')
    with op.batch_alter_table('billing_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_payments_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_billing_payments_id'))

    op.drop_table('billing_payments')
    with op.batch_alter_table('billing_invoice_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_invoice_items_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_billing_invoice_items_id'))

    op.drop_table('billing_invoice_items')
    with op.batch_alter_table('billing_quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_quotes_quote_no'))
        batch_op.drop_index(batch_op.f('ix_billing_quotes_id'))
        batch_op.drop_index(batch_op.f('ix_billing_quotes_customer_id'))

    op.drop_table('billing_quotes')
    with op.batch_alter_table('billing_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_invoices_status'))
        batch_op.drop_index(batch_op.f('ix_billing_invoices_invoice_no'))
        batch_op.drop_index(batch_op.f('ix_billing_invoices_id'))
        batch_op.drop_index(batch_op.f('ix_billing_invoices_due_date'))
        batch_op.drop_index(batch_op.f('ix_billing_invoices_customer_id'))

    op.drop_table('billing_invoices')
    with op.batch_alter_table('mfg_work_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mfg_work_orders_wo_no'))
        batch_op.drop_index(batch_op.f('ix_mfg_work_orders_status'))
        batch_op.drop_index(batch_op.f('ix_mfg_work_orders_id'))

    op.drop_table('mfg_work_orders')
    with op.batch_alter_table('mfg_bom_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mfg_bom_components_id'))
        batch_op.drop_index(batch_op.f('ix_mfg_bom_components_bom_id'))

    op.drop_table('mfg_bom_components')
    with op.batch_alter_table('hr_payrolls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hr_payrolls_period_code'))
        batch_op.drop_index(batch_op.f('ix_hr_payrolls_id'))
        batch_op.drop_index(batch_op.f('ix_hr_payrolls_employee_id'))

    op.drop_table('hr_payrolls')
    with op.batch_alter_table('hr_leave_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hr_leave_requests_status'))
        batch_op.drop_index(batch_op.f('ix_hr_leave_requests_id'))
        batch_op.drop_index(batch_op.f('ix_hr_leave_requests_employee_id'))

    op.drop_table('hr_leave_requests')
    with op.batch_alter_table('hr_leave_balances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hr_leave_balances_id'))
        batch_op.drop_index(batch_op.f('ix_hr_leave_balances_employee_id'))

    op.drop_table('hr_leave_balances')
    with op.batch_alter_table('report_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_definitions_id'))
        batch_op.drop_index(batch_op.f('ix_report_definitions_code'))

    op.drop_table('report_definitions')
    with op.batch_alter_table('mfg_boms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mfg_boms_id'))
        batch_op.drop_index(batch_op.f('ix_mfg_boms_finished_item_id'))

    op.drop_table('mfg_boms')
    with op.batch_alter_table('inv_warehouse_stock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inv_warehouse_stock_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_inv_warehouse_stock_item_id'))
        batch_op.drop_index(batch_op.f('ix_inv_warehouse_stock_id'))

    op.drop_table('inv_warehouse_stock')
    with op.batch_alter_table('fin_fiscal_periods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fin_fiscal_periods_start_date'))
        batch_op.drop_index(batch_op.f('ix_fin_fiscal_periods_id'))
        batch_op.drop_index(batch_op.f('ix_fin_fiscal_periods_end_date'))
        batch_op.drop_index(batch_op.f('ix_fin_fiscal_periods_code'))

    op.drop_table('fin_fiscal_periods')
    with op.batch_alter_table('inv_warehouses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inv_warehouses_id'))
        batch_op.drop_index(batch_op.f('ix_inv_warehouses_code'))

    op.drop_table('inv_warehouses')
    # ### end Alembic commands ###
