"""phase4: attendance 4ins etax projects fx

Revision ID: 395008e16b74
Revises: 92d17b34bcc7
Create Date: 2026-05-10 08:48:13.631635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '395008e16b74'
down_revision: Union[str, None] = '92d17b34bcc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hr_payrolls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nps', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('nhi', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('ltci', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('ei', sa.Numeric(precision=12, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hr_payrolls', schema=None) as batch_op:
        batch_op.drop_column('ei')
        batch_op.drop_column('ltci')
        batch_op.drop_column('nhi')
        batch_op.drop_column('nps')

    # ### end Alembic commands ###
