"""add currencies, lots, report_schedules, owner_id

Revision ID: 3abbbafbb518
Revises: cae9dfeefd79
Create Date: 2026-05-06 14:13:10.503973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3abbbafbb518'
down_revision: Union[str, None] = 'cae9dfeefd79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('is_base', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('currencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_currencies_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_currencies_id'), ['id'], unique=False)

    op.create_table('report_schedules',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('report_type', sa.Enum('sales_by_month', 'employees_by_department', 'top_items', 'account_balances', name='reporttype'), nullable=False),
    sa.Column('frequency', sa.Enum('daily', 'weekly', 'monthly', name='frequency'), nullable=False),
    sa.Column('recipients', sa.String(length=2000), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_schedules_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_schedules_next_run_at'), ['next_run_at'], unique=False)

    op.create_table('exchange_rates',
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('rate_to_base', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency_id', 'as_of_date', name='uq_currency_date')
    )
    with op.batch_alter_table('exchange_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exchange_rates_as_of_date'), ['as_of_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_exchange_rates_id'), ['id'], unique=False)

    op.create_table('inv_lots',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('lot_number', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('supplier', sa.String(length=200), nullable=True),
    sa.Column('serial_number', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inv_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inv_lots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inv_lots_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inv_lots_item_id'), ['item_id'], unique=False)

    with op.batch_alter_table('inv_movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lot_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_inv_movements_lot_id_inv_lots', 'inv_lots', ['lot_id'], ['id'])

    with op.batch_alter_table('sales_customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sales_customers_owner_id'), ['owner_id'], unique=False)
        batch_op.create_foreign_key('fk_sales_customers_owner_id_users', 'users', ['owner_id'], ['id'])

    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sales_orders_owner_id'), ['owner_id'], unique=False)
        batch_op.create_foreign_key('fk_sales_orders_owner_id_users', 'users', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sales_orders_owner_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sales_orders_owner_id'))
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('sales_customers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sales_customers_owner_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sales_customers_owner_id'))
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('inv_movements', schema=None) as batch_op:
        batch_op.drop_constraint('fk_inv_movements_lot_id_inv_lots', type_='foreignkey')
        batch_op.drop_column('lot_id')

    with op.batch_alter_table('inv_lots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inv_lots_item_id'))
        batch_op.drop_index(batch_op.f('ix_inv_lots_id'))

    op.drop_table('inv_lots')
    with op.batch_alter_table('exchange_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exchange_rates_id'))
        batch_op.drop_index(batch_op.f('ix_exchange_rates_as_of_date'))

    op.drop_table('exchange_rates')
    with op.batch_alter_table('report_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_schedules_next_run_at'))
        batch_op.drop_index(batch_op.f('ix_report_schedules_id'))

    op.drop_table('report_schedules')
    with op.batch_alter_table('currencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_currencies_id'))
        batch_op.drop_index(batch_op.f('ix_currencies_code'))

    op.drop_table('currencies')
    # ### end Alembic commands ###
