"""phase10: ats + consolidation + tax_adj

Revision ID: 3fa42860f63d
Revises: 1d5341fc1481
Create Date: 2026-05-11 12:45:29.177872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fa42860f63d'
down_revision: Union[str, None] = '1d5341fc1481'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
