"""add tenants, custom_fields

Revision ID: 478b9691a54e
Revises: 3abbbafbb518
Create Date: 2026-05-06 14:27:07.988682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '478b9691a54e'
down_revision: Union[str, None] = '3abbbafbb518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_field_definitions',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('field_type', sa.Enum('text', 'number', 'date', 'boolean', 'select', name='fieldtype'), nullable=False),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custom_field_definitions')),
    sa.UniqueConstraint('entity_type', 'key', name='uq_custom_field_entity_key')
    )
    with op.batch_alter_table('custom_field_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_field_definitions_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_field_definitions_id'), ['id'], unique=False)

    op.create_table('custom_field_values',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custom_field_values')),
    sa.UniqueConstraint('entity_type', 'entity_id', 'field_id', name='uq_field_value_unique')
    )
    with op.batch_alter_table('custom_field_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_field_values_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_field_values_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_field_values_field_id'), ['field_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_field_values_id'), ['id'], unique=False)

    op.create_table('tenants',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants'))
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_tenants_id'), ['id'], unique=False)

    op.create_table('user_tenants',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_user_tenants_tenant_id_tenants')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_tenants_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_tenants'))
    )
    with op.batch_alter_table('user_tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_tenants_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_tenants_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_tenants_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('sales_customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sales_customers_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_sales_customers_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sales_orders_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_sales_orders_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sales_orders_tenant_id_tenants'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sales_orders_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('sales_customers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sales_customers_tenant_id_tenants'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sales_customers_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('user_tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_tenants_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_tenants_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_user_tenants_id'))

    op.drop_table('user_tenants')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_id'))
        batch_op.drop_index(batch_op.f('ix_tenants_code'))

    op.drop_table('tenants')
    with op.batch_alter_table('custom_field_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_field_values_id'))
        batch_op.drop_index(batch_op.f('ix_custom_field_values_field_id'))
        batch_op.drop_index(batch_op.f('ix_custom_field_values_entity_type'))
        batch_op.drop_index(batch_op.f('ix_custom_field_values_entity_id'))

    op.drop_table('custom_field_values')
    with op.batch_alter_table('custom_field_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_field_definitions_id'))
        batch_op.drop_index(batch_op.f('ix_custom_field_definitions_entity_type'))

    op.drop_table('custom_field_definitions')
    # ### end Alembic commands ###
