"""phase12: qc + account_gaap_labels

Revision ID: 4d30ecc36074
Revises: 733cf7595456
Create Date: 2026-05-11 13:48:54.186470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d30ecc36074'
down_revision: Union[str, None] = '733cf7595456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fin_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ifrs_label', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('us_gaap_label', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fin_accounts', schema=None) as batch_op:
        batch_op.drop_column('us_gaap_label')
        batch_op.drop_column('ifrs_label')

    # ### end Alembic commands ###
