"""add suppliers, EDI, approval form templates

Revision ID: 6401f620efdf
Revises: 75bebd6a0325
Create Date: 2026-05-06 23:31:12.082770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6401f620efdf'
down_revision: Union[str, None] = '75bebd6a0325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_form_templates',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('schema', sa.String(length=8000), nullable=False),
    sa.Column('default_steps', sa.String(length=2000), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_form_templates'))
    )
    with op.batch_alter_table('approval_form_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_form_templates_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_approval_form_templates_id'), ['id'], unique=False)

    op.create_table('edi_messages',
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='edidirection'), nullable=False),
    sa.Column('msg_type', sa.Enum('purchase_order', 'order_ack', 'despatch', 'invoice', 'custom', name='edimessagetype'), nullable=False),
    sa.Column('partner_code', sa.String(length=50), nullable=True),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('payload_format', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('received', 'parsed', 'processed', 'failed', 'sent', name='edistatus'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('related_resource_type', sa.String(length=50), nullable=True),
    sa.Column('related_resource_id', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_edi_messages_created_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_edi_messages'))
    )
    with op.batch_alter_table('edi_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edi_messages_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_edi_messages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edi_messages_msg_type'), ['msg_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_edi_messages_partner_code'), ['partner_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_edi_messages_status'), ['status'], unique=False)

    op.create_table('suppliers',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('business_no', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('portal_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['portal_user_id'], ['users.id'], name=op.f('fk_suppliers_portal_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers'))
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_suppliers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_portal_user_id'), ['portal_user_id'], unique=False)

    op.create_table('purchase_orders',
    sa.Column('po_no', sa.String(length=50), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'sent', 'acknowledged', 'shipped', 'received', 'cancelled', name='postatus'), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_purchase_orders_created_by_id_users')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_purchase_orders_supplier_id_suppliers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_orders'))
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_po_no'), ['po_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_purchase_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('purchase_order_items',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('received_qty', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inv_items.id'], name=op.f('fk_purchase_order_items_item_id_inv_items')),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.id'], name=op.f('fk_purchase_order_items_order_id_purchase_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order_items'))
    )
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_order_items_order_id'), ['order_id'], unique=False)

    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('form_data', sa.String(length=8000), nullable=True))
        batch_op.create_index(batch_op.f('ix_approval_requests_template_id'), ['template_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_approval_requests_template_id_approval_form_templates'), 'approval_form_templates', ['template_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_approval_requests_template_id_approval_form_templates'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_approval_requests_template_id'))
        batch_op.drop_column('form_data')
        batch_op.drop_column('template_id')

    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_items_order_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_items_id'))

    op.drop_table('purchase_order_items')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_status'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_po_no'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_id'))

    op.drop_table('purchase_orders')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_portal_user_id'))
        batch_op.drop_index(batch_op.f('ix_suppliers_id'))
        batch_op.drop_index(batch_op.f('ix_suppliers_code'))

    op.drop_table('suppliers')
    with op.batch_alter_table('edi_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edi_messages_status'))
        batch_op.drop_index(batch_op.f('ix_edi_messages_partner_code'))
        batch_op.drop_index(batch_op.f('ix_edi_messages_msg_type'))
        batch_op.drop_index(batch_op.f('ix_edi_messages_id'))
        batch_op.drop_index(batch_op.f('ix_edi_messages_direction'))

    op.drop_table('edi_messages')
    with op.batch_alter_table('approval_form_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_form_templates_id'))
        batch_op.drop_index(batch_op.f('ix_approval_form_templates_code'))

    op.drop_table('approval_form_templates')
    # ### end Alembic commands ###
