"""phase3: assets crm gr supplier_invoice

Revision ID: 6f8b9bb7ad1c
Revises: 897b5bc38291
Create Date: 2026-05-10 07:23:53.016751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f8b9bb7ad1c'
down_revision: Union[str, None] = '897b5bc38291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
