"""phase11: work_center routing shop_floor_op

Revision ID: 733cf7595456
Revises: 3fa42860f63d
Create Date: 2026-05-11 13:28:02.391922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '733cf7595456'
down_revision: Union[str, None] = '3fa42860f63d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
