"""phase2: hr_holidays table

Revision ID: 897b5bc38291
Revises: 6efb1050e32c
Create Date: 2026-05-10 07:06:34.402253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '897b5bc38291'
down_revision: Union[str, None] = '6efb1050e32c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
