"""phase3b: drop crm_leads.converted_opp FK

Revision ID: 92d17b34bcc7
Revises: 6f8b9bb7ad1c
Create Date: 2026-05-10 07:26:26.319754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92d17b34bcc7'
down_revision: Union[str, None] = '6f8b9bb7ad1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_leads', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_crm_leads_converted_opportunity_id_crm_opportunities'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_leads', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_crm_leads_converted_opportunity_id_crm_opportunities'), 'crm_opportunities', ['converted_opportunity_id'], ['id'])

    # ### end Alembic commands ###
