"""add attachments and user_module_permissions

Revision ID: a028358ff873
Revises: 56c146a22826
Create Date: 2026-05-06 13:29:25.512494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a028358ff873'
down_revision: Union[str, None] = '56c146a22826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('related_type', sa.String(length=50), nullable=True),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_related_id'), ['related_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_related_type'), ['related_type'], unique=False)

    op.create_table('user_module_permissions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('admin', 'manager', 'staff', 'viewer', name='role'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'module', name='uq_user_module')
    )
    with op.batch_alter_table('user_module_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_module_permissions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_module_permissions_module'), ['module'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_module_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_module_permissions_module'))
        batch_op.drop_index(batch_op.f('ix_user_module_permissions_id'))

    op.drop_table('user_module_permissions')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_related_type'))
        batch_op.drop_index(batch_op.f('ix_attachments_related_id'))
        batch_op.drop_index(batch_op.f('ix_attachments_id'))

    op.drop_table('attachments')
    # ### end Alembic commands ###
