"""phase15: fnb recipe + haccp

Revision ID: b17a28d69812
Revises: 0e4bf3e82bc0
Create Date: 2026-05-11 14:46:55.789876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b17a28d69812'
down_revision: Union[str, None] = '0e4bf3e82bc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
