"""phase5: holiday tenant_id

Revision ID: b446a7c7b2f7
Revises: 395008e16b74
Create Date: 2026-05-10 09:44:54.042126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b446a7c7b2f7'
down_revision: Union[str, None] = '395008e16b74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hr_holidays', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_holiday_date_country'), type_='unique')
        batch_op.create_index(batch_op.f('ix_hr_holidays_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_unique_constraint('uq_holiday_date_country_tenant', ['date', 'country', 'tenant_id'])
        batch_op.create_foreign_key(batch_op.f('fk_hr_holidays_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hr_holidays', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_hr_holidays_tenant_id_tenants'), type_='foreignkey')
        batch_op.drop_constraint('uq_holiday_date_country_tenant', type_='unique')
        batch_op.drop_index(batch_op.f('ix_hr_holidays_tenant_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_holiday_date_country'), ['date', 'country'])
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###
