"""phase16b: item nutrition columns

Revision ID: d7e7f9b2d668
Revises: e8f12a4b9c10
Create Date: 2026-05-12 09:17:16.406564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7e7f9b2d668'
down_revision: Union[str, None] = 'e8f12a4b9c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_steps_approver_id_perf'))
        batch_op.drop_index(batch_op.f('ix_approval_steps_escalate_to_id_perf'))

    with op.batch_alter_table('ats_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ats_applications_converted_employee_id_perf'))

    with op.batch_alter_table('ats_job_postings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ats_job_postings_department_id_perf'))

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id_perf'))

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_customer_id_perf'))
        batch_op.drop_index(batch_op.f('ix_contracts_employee_id_perf'))
        batch_op.drop_index(batch_op.f('ix_contracts_supplier_id_perf'))

    with op.batch_alter_table('crm_opportunities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_opportunities_customer_id_perf'))

    with op.batch_alter_table('fa_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fa_assets_category_id_perf'))

    with op.batch_alter_table('fin_journal_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fin_journal_lines_account_id_perf'))
        batch_op.drop_index(batch_op.f('ix_fin_journal_lines_entry_id_perf'))

    with op.batch_alter_table('hr_employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hr_employees_department_id_perf'))

    with op.batch_alter_table('inv_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories_per_100g', sa.Numeric(precision=8, scale=2), nullable=True))
        batch_op.add_column(sa.Column('protein_g_per_100g', sa.Numeric(precision=8, scale=2), nullable=True))
        batch_op.add_column(sa.Column('carbs_g_per_100g', sa.Numeric(precision=8, scale=2), nullable=True))
        batch_op.add_column(sa.Column('fat_g_per_100g', sa.Numeric(precision=8, scale=2), nullable=True))
        batch_op.add_column(sa.Column('sodium_mg_per_100g', sa.Numeric(precision=8, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inv_items', schema=None) as batch_op:
        batch_op.drop_column('sodium_mg_per_100g')
        batch_op.drop_column('fat_g_per_100g')
        batch_op.drop_column('carbs_g_per_100g')
        batch_op.drop_column('protein_g_per_100g')
        batch_op.drop_column('calories_per_100g')

    with op.batch_alter_table('hr_employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hr_employees_department_id_perf'), ['department_id'], unique=False)

    with op.batch_alter_table('fin_journal_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fin_journal_lines_entry_id_perf'), ['entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fin_journal_lines_account_id_perf'), ['account_id'], unique=False)

    with op.batch_alter_table('fa_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fa_assets_category_id_perf'), ['category_id'], unique=False)

    with op.batch_alter_table('crm_opportunities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_opportunities_customer_id_perf'), ['customer_id'], unique=False)

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contracts_supplier_id_perf'), ['supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_employee_id_perf'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_customer_id_perf'), ['customer_id'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id_perf'), ['user_id'], unique=False)

    with op.batch_alter_table('ats_job_postings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ats_job_postings_department_id_perf'), ['department_id'], unique=False)

    with op.batch_alter_table('ats_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ats_applications_converted_employee_id_perf'), ['converted_employee_id'], unique=False)

    with op.batch_alter_table('approval_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_steps_escalate_to_id_perf'), ['escalate_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_steps_approver_id_perf'), ['approver_id'], unique=False)

    # ### end Alembic commands ###
