"""phase8: mrp + yes + reviews + campaigns + barcode

Revision ID: f1ff44bb143b
Revises: d7925dde8b32
Create Date: 2026-05-10 11:50:48.000460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1ff44bb143b'
down_revision: Union[str, None] = 'd7925dde8b32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inv_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barcode', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_inv_items_barcode'), ['barcode'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inv_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inv_items_barcode'))
        batch_op.drop_column('barcode')

    # ### end Alembic commands ###
